name: Render video
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the person"
        required: true
        default: "Hannibal Hargraves"
      image:
        description: "Image of the person"
        required: true
        default: "https://img.freepik.com/premium-photo/cheeky-young-outgoing-handsome-bearded-man-enjoying-awesome-party-inviting-come-checkout-event-pointing-left-recommend-visit-corporate-site-showing-banner-smiling-amused-white-background_176420-55530.jpg?w=2000"
      achievements:
        description: "List of the achievements"
        required: true
        default: "Lorem ipsum consectetur adipiscing elit | Sed do eiusmod tempor incididunt | Vulputate dignissim suspendisse | Lobortis scelerisque fermentum duiD | Vitae suscipit tellus mauris a diam maecenas"

jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
      - run: echo $WORKFLOW_INPUT > input-props.json
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: npm run build StarOfMonth --props="./input-props.json"
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: out/
