name: Render video
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the person"
        required: true
        default: "John Doe"
      image:
        description: "Image of the person"
        required: true
        default: "https://st.depositphotos.com/1597387/1984/i/600/depositphotos_19841901-stock-photo-asian-young-business-man-close.jpg"
      achievements:
        description: "List of the achievements"
        required: true
        default: "Achievement A | Achievement B | Achievement C | Achievement D | Achievement E | Achievement F"

jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
      - run: echo $WORKFLOW_INPUT > input-props.json
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: npm run build -- --props="./input-props.json"
      - uses: actions/upload-artifact@v2
        with:
          name: result.gif
          path: out/result.gif
